// components/Footer.tsx
import Link from 'next/link';
import Image from 'next/image';
import { MapPin, Phone, Mail, Download, Linkedin, Facebook, Instagram, Twitter, ExternalLink } from 'lucide-react';

export default function Footer() {
  const currentYear = new Date().getFullYear();

  const socialLinks = [
    { name: 'LinkedIn', href: 'https://www.linkedin.com/company/applied-technologies', icon: Linkedin },
    { name: 'Facebook', href: 'https://www.facebook.com/appliedtek', icon: Facebook },
    { name: 'Instagram', href: 'https://www.instagram.com/appliedtek', icon: Instagram },
    { name: 'Twitter', href: 'https://www.twitter.com/appliedtek', icon: Twitter },
  ];

  return (
    <footer className="bg-gradient-to-br from-brand-900 via-brand-800 to-brand-900 text-white relative overflow-hidden">
      {/* Decorative Background Pattern */}
      <div className="absolute inset-0 opacity-5">
        <div className="absolute inset-0" style={{ backgroundImage: 'url("data:image/svg+xml,%3Csvg width=\'60\' height=\'60\' viewBox=\'0 0 60 60\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cg fill=\'none\' fill-rule=\'evenodd\'%3E%3Cg fill=\'%23ffffff\' fill-opacity=\'0.4\'%3E%3Cpath d=\'M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z\'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")' }}></div>
      </div>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 relative z-10">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-12">
          {/* Company Info */}
          <div className="space-y-6">
            <div className="flex items-center gap-3">
              <div className="relative flex-shrink-0 rounded-lg p-4 bg-white">
                <Image
                  src="/images/logo.png"
                  alt="Applied Technologies Logo"
                  width={200}
                  height={200}
                  className="object-contain"
                />
              </div>
              {/* <div>
                <h3 className="text-xl font-bold text-white">
                  <span className="text-brand-red">applied</span>
                </h3>
                <span className="text-xs text-gray-400 font-medium tracking-[0.2em] uppercase">TECHNOLOGIES</span>
              </div> */}
            </div>
            <p className="text-gray-300 text-sm leading-relaxed">
              Supporting manufacturing companies in engineering to help create Innovative Products, Reduce Costs, and Shorten Development Cycles.
            </p>
            <div className="space-y-3">
              <div className="flex items-center gap-3 px-4 py-2 bg-white/5 backdrop-blur-sm rounded-lg border border-white/10">
                <span className="text-xs font-semibold text-accent">ISO</span>
                <span className="text-xs text-gray-300">305023082137Q</span>
              </div>
              <div className="flex items-center gap-3 px-4 py-2 bg-white/5 backdrop-blur-sm rounded-lg border border-white/10">
                <span className="text-xs font-semibold text-accent">ZED</span>
                <span className="text-xs text-gray-300">13052025_470695</span>
              </div>
            </div>
          </div>

          {/* Quick Links */}
          <div>
            <h3 className="text-lg font-bold mb-6 text-white">Quick Links</h3>
            <ul className="space-y-3">
              <li>
                <Link href="/" className="text-gray-300 hover:text-accent transition-all text-sm flex items-center gap-2 group">
                  <span className="w-1 h-1 bg-accent rounded-full opacity-0 group-hover:opacity-100 transition-opacity"></span>
                  Home
                </Link>
              </li>
              <li>
                <Link href="/about" className="text-gray-300 hover:text-accent transition-all text-sm flex items-center gap-2 group">
                  <span className="w-1 h-1 bg-accent rounded-full opacity-0 group-hover:opacity-100 transition-opacity"></span>
                  About Us
                </Link>
              </li>
              <li>
                <Link href="/services" className="text-gray-300 hover:text-accent transition-all text-sm flex items-center gap-2 group">
                  <span className="w-1 h-1 bg-accent rounded-full opacity-0 group-hover:opacity-100 transition-opacity"></span>
                  Services
                </Link>
              </li>
              <li>
                <Link href="/technologies" className="text-gray-300 hover:text-accent transition-all text-sm flex items-center gap-2 group">
                  <span className="w-1 h-1 bg-accent rounded-full opacity-0 group-hover:opacity-100 transition-opacity"></span>
                  Technologies
                </Link>
              </li>
              <li>
                <Link href="/machines" className="text-gray-300 hover:text-accent transition-all text-sm flex items-center gap-2 group">
                  <span className="w-1 h-1 bg-accent rounded-full opacity-0 group-hover:opacity-100 transition-opacity"></span>
                  Machines
                </Link>
              </li>
              <li>
                <Link href="/clients" className="text-gray-300 hover:text-accent transition-all text-sm flex items-center gap-2 group">
                  <span className="w-1 h-1 bg-accent rounded-full opacity-0 group-hover:opacity-100 transition-opacity"></span>
                  Clients
                </Link>
              </li>
            </ul>
          </div>

          {/* Contact Info */}
          <div>
            <h3 className="text-lg font-bold mb-6 text-white">Contact Us</h3>
            <ul className="space-y-4 text-sm text-gray-300">
              <li className="flex items-start gap-3 group">
                <MapPin className="w-5 h-5 flex-shrink-0 mt-0.5 text-accent" strokeWidth={2} />
                <span className="group-hover:text-white transition-colors">
                  Plot No.29/4, D1 Block, M.I.D.C. AKUDI INDUSTRIAL ESTATE, AKURDI, Pune- 411 019
                </span>
              </li>
              <li className="flex items-start gap-3">
                <Phone className="w-5 h-5 flex-shrink-0 text-accent" strokeWidth={2} />
                <div className="space-y-1">
                  <a href="tel:+919922837133" className="hover:text-accent transition-colors block">
                    +91 9922 83 7133
                  </a>
                  <a href="tel:+919766269444" className="hover:text-accent transition-colors block">
                    +91 9766 26 9444
                  </a>
                </div>
              </li>
              <li className="flex items-center gap-3 group">
                <Mail className="w-5 h-5 flex-shrink-0 text-accent" strokeWidth={2} />
                <a href="mailto:appliedtek@gmail.com" className="hover:text-accent transition-colors">
                  appliedtek@gmail.com
                </a>
              </li>
            </ul>
          </div>

          {/* Resources & Social */}
          <div>
            <h3 className="text-lg font-bold mb-6 text-white">Connect With Us</h3>

            {/* Social Media Links */}
            <div className="flex gap-3 mb-6">
              {socialLinks.map((social) => (
                <a
                  key={social.name}
                  href={social.href}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="group relative p-2 bg-white/5 backdrop-blur-sm rounded-lg border border-white/10 hover:border-accent hover:bg-accent/10 transition-all duration-300"
                  aria-label={social.name}
                >
                  <social.icon className="w-5 h-5 text-gray-300 group-hover:text-accent transition-colors" strokeWidth={2} />
                </a>
              ))}
            </div>

            {/* Download Brochure */}
            <a
              href="/applied_tech_presentation.pdf"
              download
              className="inline-flex items-center gap-2 px-4 py-3 bg-gradient-to-r from-brand-red to-brand-red-dark hover:from-accent hover:to-accent-light text-white rounded-lg transition-all duration-300 text-sm font-medium shadow-lg hover:shadow-xl hover:scale-105 active:scale-95"
            >
              <Download className="w-4 h-4" strokeWidth={2} />
              Download Brochure
            </a>

            {/* Proprietor */}
            <div className="mt-6 px-4 py-3 bg-white/5 backdrop-blur-sm rounded-lg border border-white/10">
              <p className="text-xs text-gray-400 mb-1">Proprietor</p>
              <p className="text-sm text-white font-semibold">Abhijeet Londhe</p>
            </div>
          </div>
        </div>

        {/* Bottom Bar */}
        <div className="border-t border-white/10 mt-12 pt-8">
          <div className="flex flex-col md:flex-row justify-between items-center gap-4">
            <p className="text-gray-400 text-sm">
              &copy; {currentYear} Applied Technologies. All rights reserved.
            </p>
            <div className="flex items-center gap-6">
              <a
                href="https://www.appliedtek.co.in"
                target="_blank"
                rel="noopener noreferrer"
                className="text-gray-300 hover:text-accent transition-colors text-sm flex items-center gap-1 group"
              >
                <span>www.appliedtek.co.in</span>
                <ExternalLink className="w-3 h-3 opacity-0 group-hover:opacity-100 transition-opacity" strokeWidth={2} />
              </a>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}

// src/lib/components/Footer.svelte
<script lang="ts">
	const currentYear = new Date().getFullYear();
</script>

<footer class="bg-slate-900 text-white py-16">
	<div class="container mx-auto px-6 lg:px-8">
		<div class="grid md:grid-cols-2 lg:grid-cols-4 gap-8 mb-12">
			<!-- Company Info -->
			<div class="lg:col-span-2">
				<div class="flex items-center space-x-3 mb-6">
					<div class="relative">
						<div class="w-12 h-12 bg-aoraki-red transform rotate-45"></div>
						<div class="absolute inset-2 bg-white transform rotate-45"></div>
						<div class="absolute inset-3 bg-aoraki-red transform rotate-45"></div>
					</div>
					<div>
						<div class="text-xl font-bold tracking-wider">AORAKI</div>
						<div class="text-sm tracking-widest text-gray-300">R E A L T Y</div>
					</div>
				</div>
				<p class="text-gray-300 leading-relaxed max-w-md mb-6">
					Creating innovative and high-quality office spaces, commercial complexes, and residential housing flats since 2002. Building communities where businesses and families thrive.
				</p>
				<div class="flex space-x-4">
					<a href="https://facebook.com" aria-label="Facebook" class="w-10 h-10 bg-aoraki-red rounded-full flex items-center justify-center hover:bg-red-700 transition-colors">
						<svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
							<path fill-rule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z" clip-rule="evenodd" />
						</svg>
					</a>
					<a href="https://twitter.com" aria-label="Twitter" class="w-10 h-10 bg-aoraki-red rounded-full flex items-center justify-center hover:bg-red-700 transition-colors">
						<svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
							<path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
						</svg>
					</a>
					<a href="https://pinterest.com" aria-label="Pinterest" class="w-10 h-10 bg-aoraki-red rounded-full flex items-center justify-center hover:bg-red-700 transition-colors">
						<svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
							<path fill-rule="evenodd" d="M12.017 0C5.396 0 .029 5.367.029 11.987c0 5.079 3.158 9.417 7.618 11.174-.105-.949-.199-2.403.041-3.439.219-.937 1.406-5.957 1.406-5.957s-.359-.72-.359-1.781c0-1.663.967-2.911 2.168-2.911 1.024 0 1.518.769 1.518 1.688 0 1.029-.653 2.567-.992 3.992-.285 1.193.6 2.165 1.775 2.165 2.128 0 3.768-2.245 3.768-5.487 0-2.861-2.063-4.869-5.008-4.869-3.41 0-5.409 2.562-5.409 5.199 0 1.033.394 2.143.889 2.741.099.12.112.225.085.346-.09.375-.294 1.194-.334 1.363-.053.225-.172.271-.402.165-1.495-.69-2.433-2.878-2.433-4.646 0-3.776 2.748-7.252 7.92-7.252 4.158 0 7.392 2.967 7.392 6.923 0 4.135-2.607 7.462-6.233 7.462-1.214 0-2.357-.629-2.758-1.378l-.749 2.848c-.269 1.045-1.004 2.352-1.498 3.146 1.123.345 2.306.535 3.55.535 6.624 0 11.99-5.367 11.99-11.988C24.007 5.367 18.641.001 12.017.001z" clip-rule="evenodd" />
						</svg>
					</a>
					<a href="https://linkedin.com" aria-label="LinkedIn" class="w-10 h-10 bg-aoraki-red rounded-full flex items-center justify-center hover:bg-red-700 transition-colors">
						<svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
							<path fill-rule="evenodd" d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" clip-rule="evenodd" />
						</svg>
					</a>
				</div>
			</div>

			<!-- Quick Links -->
			<div>
				<h3 class="text-lg font-semibold mb-6">Quick Links</h3>
				<ul class="space-y-4">
					<li><a href="#home" class="text-gray-300 hover:text-white transition-colors">Home</a></li>
					<li><a href="#about" class="text-gray-300 hover:text-white transition-colors">About Us</a></li>
					<li><a href="#services" class="text-gray-300 hover:text-white transition-colors">Services</a></li>
					<li><a href="#projects" class="text-gray-300 hover:text-white transition-colors">Projects</a></li>
					<li><a href="#contact" class="text-gray-300 hover:text-white transition-colors">Contact</a></li>
				</ul>
			</div>

			<!-- Services -->
			<div>
				<h3 class="text-lg font-semibold mb-6">Our Services</h3>
				<ul class="space-y-4">
					<li><span class="text-gray-300">Office Spaces</span></li>
					<li><span class="text-gray-300">Commercial Complexes</span></li>
					<li><span class="text-gray-300">Residential Housing</span></li>
					<li><span class="text-gray-300">Project Management</span></li>
					<li><span class="text-gray-300">Architecture Consulting</span></li>
				</ul>
			</div>
		</div>

		<!-- Bottom Section -->
		<div class="border-t border-gray-700 pt-8">
			<div class="flex flex-col md:flex-row justify-between items-center">
				<p class="text-gray-300 text-sm mb-4 md:mb-0">
					© {currentYear} Aoraki Realty. All rights reserved.
				</p>
				<div class="flex space-x-6 text-sm">
					<a href="/privacy" class="text-gray-300 hover:text-white transition-colors">Privacy Policy</a>
					<a href="/terms" class="text-gray-300 hover:text-white transition-colors">Terms of Service</a>
					<a href="/cookies" class="text-gray-300 hover:text-white transition-colors">Cookie Policy</a>
				</div>
			</div>
		</div>
	</div>
</footer>
